# Generated by Django 5.1.2 on 2025-02-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_course_courseenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждено')], default='pending', max_length=20),
        ),
    ]
