# Generated by Django 5.1.2 on 2025-02-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_courseenrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_file',
            field=models.FileField(blank=True, null=True, upload_to='course_files/'),
        ),
    ]
