# Generated by Django 5.1.2 on 2025-02-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_course_course_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не пройден'), ('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждено'), ('completed', 'Пройден')], default='not_started', max_length=20),
        ),
    ]
